namespace: &{kube.ns}
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/forgeops-secrets
  - ../../../base/7.0/ds/cts
  - ../../../base/7.0/ds/idrepo
  - ../../../base/am
  - ../../../base/amster
  - ../../../base/idm
  - ../../../base/end-user-ui
  - ../../../base/login-ui
  - ../../../base/admin-ui
  - ../../../base/7.0/ingress
  - ../../../base/ldif-importer

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: platform-config
    data:
      FQDN: &{fr.fqdn}