namespace: iot
commonLabels:
  app.kubernetes.io/part-of: "forgerock"
resources:
  - ../../../base/kustomizeConfig
  - ../../../base/secrets
  - ../../../base/7.0/ds/cts
  - ../../../base/7.0/ds/idrepo
  - ../../../base/am-cdk
  - ../../../base/amster
  - ../../../base/idm-cdk
  - ../../../base/rcs-agent
  - ../../../base/end-user-ui
  - ../../../base/login-ui
  - ../../../base/admin-ui
  - ../../../base/ingress
  - ../../../base/ldif-importer

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: platform-config
    data:
      FQDN: iot.iam.example.com