version: '3'

services:

  hivemq:
    image: hivemq:latest
    container_name: hivemq
    stdin_open: true
    tty: true
    build: mqtt-broker
    ports:
      - "8080:8080"
      - "1883:1883"
    networks:
      iot_net:
        ipv4_address: 172.16.0.31
    hostname: hivemq
    extra_hosts:
      - "iot.iam.example.com:$AM_IP_ADDRESS"
    environment:
      - JAVA_OPTS=-DdiagnosticMode=true

  mqtt-client:
    image: mqtt-client:latest
    container_name: mqtt-client
    stdin_open: true
    tty: true
    build: mqtt-client
    networks:
      iot_net:
        ipv4_address: 172.16.0.32
    hostname: mqtt-client
    extra_hosts:
      - "iot.iam.example.com:$AM_IP_ADDRESS"
      - "broker.hivemq.com:172.16.0.31"
    environment:
      - AM_URL=https://iot.iam.example.com/am
      - MQTT_SERVER_URL=tcp://broker.hivemq.com:1883

networks:
  iot_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
