@startuml

skinparam sequence {
    ArrowFontColor #062b8c
    ArrowColor #062b8c
    LifeLineBorderColor #062b8c

    ParticipantBorderColor #062b8c
    ParticipantBackgroundColor #fc6700
    ParticipantFontColor #062b8c

    ActorBorderColor #062b8c
    ActorBackgroundColor #fc6700
    ActorFontColor #062b8c
}

participant Device as dv
participant "FR Platform" as fr
participant "HiveMQ" as rb

rb -> fr: Get JSON web key set
fr --> rb
dv -> fr : Authenticate
dv <-- fr
dv -> fr : Request OAuth 2.0\naccess token
dv <-- fr
dv -> rb: Connect\npwd = token
rb -> rb : Verify token
dv <-- rb
dv -> rb: Publish\Subscribe

@enduml