namespace: &{kube.ns}
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
  - ../../base/kustomizeConfig
  - ../../base/forgeops-secrets
  - ../../base/ds/cts
  - ../../base/ds/idrepo
  - ../../base/am
  - ../../base/amster
  - ../../base/idm
  - ../../base/end-user-ui
  - ../../base/login-ui
  - ../../base/admin-ui
  - ../../base/ingress
  - ../../base/ldif-importer

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: platform-config
    data:
      FQDN: &{fr.fqdn}