@startuml

skinparam component {
  FontColor #062b8c
  BackgroundColor #fc6700
  BorderColor #062b8c
  BackgroundColor<<third party>> azure
  ArrowColor #062b8c
  ArrowFontColor #062b8c
}
skinparam node {
  BorderColor #062b8c
  FontColor #062b8c
}
skinparam frame {
  BorderColor Grey
  FontColor Grey
}

frame "Platform Tier" {
    [ForgeRock Identity Platform] as fr
}
frame "Edge Tier" {
    frame "Class 1 Device" {
        [IoT SDK] as gc
    }
    frame "Class 2 Device" {
        [IoT SDK] as ac
    }
    frame "Class 0 Device" {
        [Bespoke Software] as cc <<third party>>
    }
    frame "Gateway Device" {
        [IoT Gateway] as gt
    }
}
gt -up-> fr : HTTP/TLS
ac -up-> fr : HTTP/TLS
gc -up-> gt : COAP/DTLS
cc -right-> ac : Bespoke\nProtocol
cc -left-> gc : Bespoke\nProtocol
@enduml