@startuml
title ForgeRock IoT in accordance with RFC 7228

frame "Edge Tier" {
    frame "Class 2 Device" {
        [Things SDK] as amclient1
    }
    frame "Class 1 Device" {
        [Things SDK] as iecclient1
    }
    frame "Class 0 Device" {
        [Bespoke Software] as customclient1
    }

    frame "IoT Gateway" {
        [Identity Edge Controller] as iec
        [Things SDK] as iecclient2
    }
}
frame "Platform Tier" {
    node "ForgeRock Platform" {
        [Access Management] as am
    }
}
iec -right-> am : HTTP/TLS
amclient1 --> am : HTTP/TLS
iecclient1 --> iec : COAP/DTLS
iecclient2 -right-> iec : COAP/DTLS
customclient1 --> iecclient2 : Bespoke\nProtocol
@enduml