@startuml

skinparam sequence {
    ArrowFontColor #062b8c
    ArrowColor #062b8c
    LifeLineBorderColor #062b8c

    ParticipantBorderColor #062b8c
    ParticipantBackgroundColor #fc6700
    ParticipantFontColor #062b8c

    ActorBorderColor #062b8c
    ActorBackgroundColor #fc6700
    ActorFontColor #062b8c
}

actor "Thing" as thing
participant "Access Management" as am
participant "Directory Services" as ds

thing -> thing : generate key pair
thing -> thing : activate
thing -> am : register with signed JWT
am -> am : verify JWT
am -> ds : create identity\nwith public key
am --> thing : return session token

@enduml