@startuml

skinparam sequence {
    ArrowFontColor #062b8c
    ArrowColor #062b8c
    LifeLineBorderColor #062b8c

    ParticipantBorderColor #062b8c
    ParticipantBackgroundColor #fc6700
    ParticipantFontColor #062b8c

    ActorBorderColor #062b8c
    ActorBackgroundColor #fc6700
    ActorFontColor #062b8c
}

actor "Manufacturer\\\nSoftware Publisher" as man
actor "Thing" as thing
participant "Access Management" as am
participant "Directory Services" as ds

thing -> thing : generate key pair
man -> thing : retrieve thing public key
man -> thing : add key pair\nand software statement
man -> am : add software statement verification keys

thing -> thing : activate
thing -> am : register with\nsoftware statement
am -> am : verify software statement
am -> am : generate unique ID
am -> ds : create identity\nwith public key
am --> thing : return session token

thing -> am : request thing attributes
am --> thing : thing unique ID
thing -> am : authenticate with\nclient assertion
am -> am : verify client assertion
am --> thing : return session token

@enduml