version: '3'

services:

  things:
    image: things-rabbitmq:latest
    container_name: things
    stdin_open: true
    tty: true
    build: ./things
    networks:
      iot_net:
        ipv4_address: 172.16.0.13
    hostname: iot-things
    extra_hosts:
      - "rabbit.example.com:172.16.0.14"
    environment:
      - AM_URL=https://iot.iam.example.com/am
      - AM_REALM=/
      - AM_TREE=RegisterThings
      - MQTT_SERVER_URL=tcp://rabbit.example.com:1883
    volumes:
      - ./things/rabbit-demo:/usr/local/go/src/rabbit-demo

  rabbitmq:
    image: rabbitmq-integration-example:latest
    container_name: rabbitmq
    stdin_open: true
    tty: true
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "1883:1883"
      - "15672:15672"
    networks:
      iot_net:
        ipv4_address: 172.16.0.14
    hostname: iot-rabbitmq

networks:
  iot_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
