@startuml

skinparam component {
  FontColor #062b8c
  BackgroundColor #fc6700
  BorderColor #062b8c
  BackgroundColor<<third party>> azure
  BackgroundColor<<RabbitMQ>> TECHNOLOGY
  ArrowColor #062b8c
  ArrowFontColor #062b8c
}
skinparam node {
  BorderColor #062b8c
  FontColor #062b8c
}
skinparam frame {
  BorderColor Grey
  FontColor Grey
}

frame "Edge Tier" {
    frame "Device" {
        [Thing SDK] as ac
        [MQTT Client] as mc <<third party>>
    }
}
frame "Platform Tier" {
    node "ForgeRock Identity Platform" {
        [Access Management] as am
    }
    node "RabbitMQ" {
        [MQTT Broker] as mqtt <<RabbitMQ>>
        [OAuth 2.0 Plugin] as oauth2 <<RabbitMQ>>
    }
}
ac -up-> am : Onboard &\nAuthorise
ac -right-> mc
mc -up-> mqtt : Publish\n(OAuth 2.0 Token)
mqtt -left-> oauth2 : Verify Token
@enduml